#!/usr/local/bin/python3

import schema

__doc__ = '''
autolite control tool.

Usage:
    autolite task list [<name>] [-l | -J | -Y] [-r]
    autolite task create <name> ({sched_flags})
                     [--command=<exe>] [--condition=<exe>]
    autolite (task | system) (read | delete) <name>
    autolite task set <name> schedule ({sched_flags})
    autolite task set <name> (condition | command) <exe>
    autolite task set <name> parent <parent>
    autolite task set <name> email <email>
    autolite task reset <name> [--force]
    autolite system list [-1 | -l | -J | -Y]
    autolite system create <name> [--ip <ip>]
                     [--installer=<exe>] [--cleaner=<exe>] [--monitor=<exe>] [--config=<exe>]
    autolite system set <name> ip <ip>
    autolite system set <name> comment <text>
    autolite system set <name> (installer | cleaner | monitor | config) <exe>
    autolite system (acquire | install | clean | monitor | config) <name>
    autolite system release <name> [--force]
    autolite test [-- <arg>...]

Options:
    -h --help               Show this screen.
    --version               Show version.
    -v --verbose            Higher verbosity messages.
    -l --long               Table list long format.
    -1 --col-1              Table list main column only.
    -J --JSON               List with JSON format.
    -Y --YAML               List with YAML format.
    -r --recursive          Task recursive listing, by lineage, including subtask state summary.
    --force                 Force the command.
{sched_opts}
    --command <exe>         Task command executable.
    --condition <exe>       Task condition executable (returns true|false).
    --installer <exe>       System installation executable.
    --cleaner <exe>         System cleaning executable.
    --monitor <exe>         System monitoring executable.
    --config <exe>          System configuration executable.
'''.format(
    sched_flags=' | '.join(('--' + sched) for sched in schema.SCHEDULES),
    sched_opts='\n'.join(
        '    -{upchar}, --{sched:17} Set task schedule to \'{sched}\'.'.format(sched=sched, upchar=sched[0].upper())
        for sched in schema.SCHEDULES),
)

import os
import sys

import db
import consts
import autolite_task
import autolite_system
from common import chdir_context
from verbosity import set_verbosity, get_verbosity_level

SELF_ABS_PATH, SELF_FULL_DIR, SELF_SUB_DIR = consts.get_self_path_dir(__file__)

def autolite(arguments):
    db.init()

    if arguments['task']:
        autolite_task.menu(arguments)

    elif arguments['system']:
        autolite_system.menu(arguments)

    elif arguments['test']:
        os.system('./autolite_test ' +
                  '-{} '.format('v' * max(get_verbosity_level(), 1)) +
                  ' '.join(arg for arg in arguments['<arg>'] if arg != '--'))


def _verbosity_flags(doc: str) -> str:
    return '\n'.join(
        (d + ' [-v | -vv]') if d.lstrip().startswith('autolite ') else d
        for d in doc.split('\n')
    )


if __name__ == '__main__':
    rc = 1

    with chdir_context(SELF_FULL_DIR):
        from docopt import docopt

        with open(os.path.join(SELF_FULL_DIR, 'version')) as ver_file:
            arguments = docopt(_verbosity_flags(__doc__), version=ver_file.read())

        set_verbosity(arguments['--verbose'])

        if get_verbosity_level() > 1:
            print(arguments)

        rc = autolite(arguments)

    sys.exit(rc)
