#!/bin/bash

function ensure_minor {
	prog=$1
	install_opt=$2
	shift 2

	which $prog 2>&1 1>/dev/null
	if [ $? == '0' ]
	then
		test -L /usr/local/bin/$prog
		if [ $? != '0' ]
		then
			sudo ln -sf `which $prog` /usr/local/bin/$prog
		fi

	else
		echo Missing $prog in PATH - trying to locate...
		for m in `seq 9 -1 1`
		do
			which $prog.$m 2>1 2>/dev/null
			if [ $? == '0' ]
			then
				sudo ln -sf `which $prog.$m` /usr/local/bin/$prog
				break
			fi
		done
		echo -e "\e[31m[x]\e[0m Failed locating $prog.x! try: $install_opt"
		exit 1
	fi

}
&ensure_minor python3 "https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7"
ensure_minor pip3 "sudo yum -y install python36u-pip"

python3 install.py $@
